FROM php:8.2-fpm AS php-fpm82-nginx
ARG TIMEZONE

LABEL Maintainer="email@javier-rodriguez.com"

#Configuration
ENV ACCEPT_EULA=Y
ARG DEBIAN_FRONTEND=noninteractive

#Utilities
RUN apt-get update && apt-get install -y \
    git \
    openssl \
    unzip \
    wget \
    supervisor \
    cron \
    htop \
    zip \
    vim \
    lsof \
    apt-utils \
    librabbitmq-dev  


RUN apt-get install -y \
    nginx

#Php Unit 8.0
RUN wget -O phpunit.phar https://phar.phpunit.de/phpunit-8.0.6.phar && \
    chmod +x phpunit.phar &&  cp phpunit.phar /usr/local/lib/php

#Install Composer.
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer --version

#TimeZone
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN echo '[PHP]\ndate.timezone ="Europe/Madrid"' > /usr/local/etc/php/php.ini

#PHP Extensions
RUN apt-get install -y libxml2-dev libmcrypt-dev libcurl4-openssl-dev
RUN docker-php-ext-install bcmath
RUN docker-php-ext-install pcntl
RUN docker-php-ext-install sockets
RUN docker-php-ext-install dom
RUN docker-php-ext-install session
RUN docker-php-ext-install pdo
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install curl
RUN pecl install xmlrpc-1.0.0RC3
RUN docker-php-ext-install xmlwriter
RUN docker-php-ext-install xml
RUN docker-php-ext-install opcache
RUN docker-php-ext-install soap
RUN apt-get install -y libonig-dev
RUN docker-php-ext-install mbstring
RUN curl -sSL https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions -o - | sh -s \
      http

RUN apt-get update -y && apt-get install -y libwebp-dev libjpeg62-turbo-dev libpng-dev libxpm-dev \
    libfreetype6-dev zlib1g-dev libzip-dev

RUN docker-php-ext-install zip
RUN docker-php-ext-install gd

##Install Imagemagick & PHP Imagick ext
RUN apt-get update; \
    apt-get install -y libmagickwand-dev; \
    pecl install imagick; \
    docker-php-ext-enable imagick;

##Install apmq
RUN pecl install amqp \
&& docker-php-ext-enable amqp

##Configuración XDEBug
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug
RUN echo 'xdebug.remote_port=9000' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo 'xdebug.remote_enable=1' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo 'xdebug.remote_connect_back=1' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo 'xdebug.idekey = PHPSTORM' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo 'xdebug.remote_autostart=1' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo 'xdebug.max_nesting_level=4096' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

##MAX FILE SIZE
RUN echo 'upload_max_filesize = 20M' >> /usr/local/etc/php/php.ini
RUN echo 'post_max_size = 40M' >> /usr/local/etc/php/php.ini
RUN echo 'display_errors = Off' >> /usr/local/etc/php/php.ini
RUN echo 'error_reporting = E_ERROR' >> /usr/local/etc/php/php.ini
RUN echo 'memory_limit = 512M' >> /usr/local/etc/php/php.ini

##MODIFY TIME OUT
RUN echo 'max_execution_time = 600' >> /usr/local/etc/php/php.ini

#Clean
RUN rm -rf /var/lib/apt/lists/*


COPY nginx-site.conf /etc/nginx/sites-enabled/default
COPY entrypoint.sh /etc/entrypoint.sh
RUN chmod +x /etc/entrypoint.sh

WORKDIR /var/www

EXPOSE 80 443

ENTRYPOINT [ "/etc/entrypoint.sh" ]