name: Master Dispatcher

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.collect.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed folders
        id: filter
        uses: dorny/paths-filter@v3
        with:
          base: 'main'
          filters: |
            php74:
              - 'php74/**'
            php82:
              - 'php82/**'
            php84:
              - 'php84/**'

      - name: Debug filters
        run: |
          echo "php74 => ${{ steps.filter.outputs.php74 }}"
          echo "php82 => ${{ steps.filter.outputs.php82 }}"
          echo "php84 => ${{ steps.filter.outputs.php84 }}"

      - name: Collect changed versions
        id: collect
        run: |
          CHANGED=""
          if [ "${{ steps.filter.outputs.php74 }}" = "true" ]; then CHANGED="$CHANGED php74"; fi
          if [ "${{ steps.filter.outputs.php82 }}" = "true" ]; then CHANGED="$CHANGED php82"; fi
          if [ "${{ steps.filter.outputs.php84 }}" = "true" ]; then CHANGED="$CHANGED php84"; fi
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

  dispatch-builds:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - name: Trigger php74 build
        if: contains(needs.detect-changes.outputs.changed, 'php74')
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: php74-build.yml
          ref: main

      - name: Trigger php82 build
        if: contains(needs.detect-changes.outputs.changed, 'php82')
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: php82-build.yml
          ref: main

      - name: Trigger php84 build
        if: contains(needs.detect-changes.outputs.changed, 'php84')
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: php84-build.yml
          ref: main
