name: Master Dispatcher

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      # Detecta qué carpetas han cambiado
      - name: Filter changed folders
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            PHP8_2:
              - 'PHP8_2/**'
      
      # Convierte los filtros en una sola cadena de versiones
      - name: Collect changed versions
        id: collect
        run: |
          CHANGED=""
          if [ "${{ steps.filter.outputs.PHP8_2 }}" == "true" ]; then CHANGED="PHP8_2"; fi
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT
      
      # Debugging output
      - name: Debug
        run: |
          echo "php8_2 => ${{ steps.filter.outputs.PHP8_2 }}"


  dispatch-builds:
    needs: detect-changes
    runs-on: ubuntu-latest
    steps:
      - name: Trigger PHP74
        if: contains(needs.detect-changes.outputs.changed, '7_4')
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: php74-build.yml
          ref: main
      - name: Trigger PHP81
        if: contains(needs.detect-changes.outputs.changed, '8_1')
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: php81-build.yml
          ref: main
      - name: Trigger PHP82
        if: steps.filter.outputs.PHP8_2 == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: php82-build.yml
          ref: main
      
