name: Build PHP 8.2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push PHP 8.2 image
        uses: docker/build-push-action@v6
        with:
          context: ./8_2
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm-nginx:php82
            ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm-nginx:8
            ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm-nginx:latest
