name: Build PHP 8.2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push PHP 8.2 image
        uses: docker/build-push-action@v6
        with:
          context: ./php82
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm-nginx:php82
            ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm-nginx:php8
            ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm-nginx:latest
      
      - name: Trivy Scan PHP 8.2
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm-nginx:php82
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
      
      - name: Extract Trivy summary
        id: summary
        run: |
          CRITICAL=$(jq '.Results[].Vulnerabilities[]? | select(.Severity=="CRITICAL")' trivy-report.json | wc -l)
          HIGH=$(jq '.Results[].Vulnerabilities[]? | select(.Severity=="HIGH")' trivy-report.json | wc -l)
          if [ "$CRITICAL" -gt 0 ]; then
            LEVEL="CRITICAL"
          elif [ "$HIGH" -gt 0 ]; then
            LEVEL="HIGH"
          else
            LEVEL="SAFE"
          fi
          echo "level=$LEVEL" >> $GITHUB_OUTPUT
      
      - name: Update README with Trivy result
        run: |
          sed -i "s|<!--TRIVY_LEVEL-->.*<!--TRIVY_LEVEL-->|<!--TRIVY_LEVEL-->${{ steps.summary.outputs.level }}<!--TRIVY_LEVEL-->|" README.md
        
      - name: Commit README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Trivy security level [skip ci]"
          token: ${{ secrets.GH_PAT }}
